<!DOCTYPE html>
<html lang="en">
<head>
<title>Learn Center | Contacts</title>
<meta charset="utf-8">

</head>
<body id="page5">
<div class="body1">
  <div class="main">
    <!-- header -->
    <header>
      <div class="wrapper">
        <nav>
          <ul id="menu">
            <li><a href="<?php echo $this->url(
            array('controller'=>'about')) ?>">About</a></li>
            <li><a href="<?php echo $this->url(
            array('controller'=>'courses')) ?>">Courses</a></li>
            <li><a href="<?php echo $this->url(
            array('controller'=>'programs')) ?>">Programs</a></li>
            <li><a href="teachers.html">Teachers</a></li>
            <li><a href="admissions.html">Admissions</a></li>
            <li class="end"><a href="contacts.html">Contacts</a></li>
             <li><a href="<?php echo $this->url(
            array('controller'=>'register'),'default', true) ?>">Signup</a></li>
          </ul>
          </ul>
        </nav>
        <ul id="icons">
          <li><a href="#"><img src="images/icons1.jpg" alt=""></a></li>
          <li><a href="#"><img src="images/icons2.jpg" alt=""></a></li>
        </ul>
      </div>
      <div class="wrapper">
        <h1><a href="index.html" id="logo">Learn Center</a></h1>
      </div>
      <div id="slogan"> We Will Open The World<span>of knowledge for you!</span> </div>
    </header>
    <!-- / header -->
  </div>
</div>

<script type="text/javascript">Cufon.now();</script>
</body>
</html>