<?php echo $this->doctype() ;

$controller = Zend_Controller_Front::getInstance();
  $baseUrl=$controller->getBaseUrl();

?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>

  <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/reset.css" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/layout.css" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/style.css" type="text/css" media="all">
<script type="text/javascript" src="<?php echo $baseUrl;?>/js/jquery-1.5.2.js" ></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/js/cufon-yui.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/js/cufon-replace.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/js/Molengo_400.font.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/js/Expletus_Sans_400.font.js"></script>
</head>
<body>


<?php echo $this->layout()->content ?>

</body>
</html>
