function Section (sectionName,sectionID,secQues,secTime,secMarks,secNegMark,consumedsecTime,consumedsecq)
		{
			this.sectionName=sectionName;
			this.sectionID=sectionID;
			this.secQues=secQues;
			this.secTime=secTime;
			this.secMarks=secMarks;
			this.secNegMark=secNegMark;
			this.consumedsecTime=consumedsecTime;
			this.consumedsecq=consumedsecq;
		}
		
		function Question(qname,type,qstring,response,img,fid,fname,b_time,diff,testids,sectionid,flag)
		{
			this.qname=qname;
			this.type=type;
			this.qstring=qstring;
			this.response=response;
			this.img=img;
			this.fid=fname;
			this.fname=fid;
			this.b_time=b_time;
			this.diff=diff;
			this.testids=testids;
			this.sectionid=sectionid
			this.flag=flag;
		}
		//document.write(a);
		var zin=1,top=0, mycount=0, waitTime=6000 , qright=0, mycomment,nowtime;
		var global=new Array(3);
		var abc,xyz,tm;
		var tname = "Reading Comprehension";
		var tid = "src366";
		var cname = "RC: 1" ;
		var gg = "d";
		var recent, recent2, recdone=false, opera7, opera=CheckOpera56();
		P7_OpResizeFix();
		function P7_OpResizeFix(a) { //v1.1 by PVII
		if(!window.opera){return;}if(!document.p7oprX){
		 document.p7oprY=window.innerWidth;document.p7oprX=window.innerHeight;
		 document.onmousemove=P7_OpResizeFix;
		 }else{if(document.p7oprX){
		  var k=document.p7oprX-window.innerHeight;
		  var j=document.p7oprY - window.innerWidth;
		  if(k>1 || j>1 || k<-1 || j<-1){
		  document.p7oprY=window.innerWidth;document.p7oprX=window.innerHeight;
		  do_reposition();}}}
		}
		function cachewrite(s,idx){global[idx]+=s;}
		function CheckOpera56()
		{
		var version;
		if (navigator.userAgent.toLowerCase().indexOf('opera') == -1) return false;
		version=parseInt(navigator.appVersion.toLowerCase());
		if (version>6) {opera7=true; return false;}
		if (version<5) return false;
		return true;
		}resp=new Array("<font face=Arial size=2>North pole to south pole</font>","<font face=Arial size=2> South pole to north pole</font>","<font face=Arial size=2> South pole to south pole</font>","<font face=Arial size=2> North pole to north pole</font>");comm="";valu="";ques0 = new Question(
						"Question0",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Magnetic lines of force travel from _______ outside the magnet</b></font>",
						resp,
						"24415",
						"24415",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>sublimation</font>","<font face=Arial size=2> condensation</font>","<font face=Arial size=2> melting</font>","<font face=Arial size=2> boiling</font>");comm="";valu="";ques1 = new Question(
						"Question1",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The phase change represented by the equation I<sub>2 </sub>(s) &rarr; I<sub>2 </sub>(g) is called</b></font>",
						resp,
						"24379",
						"24379",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Edison</font>","<font face=Arial size=2> Babbage</font>","<font face=Arial size=2> Mac Millen</font>","<font face=Arial size=2> Rangabhashyam</font>");comm="";valu="";ques2 = new Question(
						"Question2",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Who among the following is associated with the invention of computers?</b></font>",
						resp,
						"24481",
						"24481",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>boron trichloride</font>","<font face=Arial size=2> oxygen difluoride</font>","<font face=Arial size=2> silicon tetrafluoride</font>","<font face=Arial size=2> selenium difluoride</font>");comm="";valu="";ques3 = new Question(
						"Question3",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Which compound is probably most polar of the following?</b></font>",
						resp,
						"24416",
						"24416",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>pivotal joints</font>","<font face=Arial size=2> .ball and socket joints</font>","<font face=Arial size=2> hinge joints</font>","<font face=Arial size=2> fixed joints</font>");comm="";valu="";ques4 = new Question(
						"Question4",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Name the joints which can not move.</b></font>",
						resp,
						"24426",
						"24426",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Penicillin</font>","<font face=Arial size=2> X-ray</font>","<font face=Arial size=2> Streptomycin</font>","<font face=Arial size=2> Telephone</font>");comm="";valu="";ques5 = new Question(
						"Question5",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Alexander Fleming discovered</b></font>",
						resp,
						"24375",
						"24375",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Energy</font>","<font face=Arial size=2> Speed</font>","<font face=Arial size=2> Distance</font>","<font face=Arial size=2> Intensity</font>");comm="";valu="";ques6 = new Question(
						"Question6",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Light year is related to</b></font>",
						resp,
						"24422",
						"24422",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>They contain carbon-which is nonpolar</font>","<font face=Arial size=2> &nbsp;They have a high degree of symmetry</font>","<font face=Arial size=2> &nbsp;The electronegativities of carbon and hydrogen are similar</font>","<font face=Arial size=2> &nbsp;More than one of the above</font>");comm="";valu="";ques7 = new Question(
						"Question7",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Why are organic molecules usually not very polar?</b></font>",
						resp,
						"24461",
						"24461",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Ohm</font>","<font face=Arial size=2> Watt</font>","<font face=Arial size=2> Ampere</font>","<font face=Arial size=2> None of these</font>");comm="";valu="";ques8 = new Question(
						"Question8",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The unit of current is</b></font>",
						resp,
						"24373",
						"24373",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Non-luminous</font>","<font face=Arial size=2> Opaque</font>","<font face=Arial size=2> Transparent</font>","<font face=Arial size=2> Luminous</font>");comm="";valu="";ques9 = new Question(
						"Question9",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Bodies that radiate light are called?</b></font>",
						resp,
						"24456",
						"24456",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>The pencil exerts more gravitational force on the Earth than the Earth exerts on the pencil</font>","<font face=Arial size=2> The pencil exerts the same gravitational force on the Earth that the Earth exerts on the pencil</font>","<font face=Arial size=2> The pencil exerts less gravitational force on the Earth than the Earth exerts on the pencil</font>","<font face=Arial size=2> None of the above</font>");comm="";valu="";ques10 = new Question(
						"Question10",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>A pencil sits still on a professor&rsquo;s desk. Which of the following statements is true?</b></font>",
						resp,
						"24488",
						"24488",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>soluble in water</font>","<font face=Arial size=2> insoluble in water</font>","<font face=Arial size=2> a solid</font>","<font face=Arial size=2> more than one of the above</font>");comm="";valu="";ques11 = new Question(
						"Question11",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The symbol (s) after a chemical compound lets you know that it is:</b></font>",
						resp,
						"24419",
						"24419",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>metals</font>","<font face=Arial size=2> nonmetals</font>","<font face=Arial size=2> metalloids</font>","<font face=Arial size=2> transition metals</font>");comm="";valu="";ques12 = new Question(
						"Question12",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Which of the following typically has a low melting point?</b></font>",
						resp,
						"24408",
						"24408",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Don&rsquo;t depend on the amount of material present.</font>","<font face=Arial size=2> Depend on the amount of material present.</font>","<font face=Arial size=2> Cannot be measured without performing a chemical reaction.</font>","<font face=Arial size=2> None of the above is correct.</font>");comm="";valu="";ques13 = new Question(
						"Question13",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Intrinsic properties are properties that:</b></font>",
						resp,
						"24440",
						"24440",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Newton</font>","<font face=Arial size=2> Dalton</font>","<font face=Arial size=2> Copernicus</font>","<font face=Arial size=2> Einstein</font>");comm="";valu="";ques14 = new Question(
						"Question14",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The scientist who first discovered that the earth revolves round the sun was</b></font>",
						resp,
						"24464",
						"24464",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Barometer</font>","<font face=Arial size=2> Hydrometer</font>","<font face=Arial size=2> Polygraph</font>","<font face=Arial size=2> Seismograph</font>");comm="";valu="";ques15 = new Question(
						"Question15",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The intensity of an earthquake is measured with a</b></font>",
						resp,
						"24465",
						"24465",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>32</font>","<font face=Arial size=2> 196</font>","<font face=Arial size=2> 206</font>","<font face=Arial size=2> 512</font>");comm="";valu="";ques16 = new Question(
						"Question16",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>What is the total number of bones in the human body?</b></font>",
						resp,
						"24397",
						"24397",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Fats</font>","<font face=Arial size=2> Proteins</font>","<font face=Arial size=2> Carbohydrates</font>","<font face=Arial size=2> Roughage</font>");comm="";valu="";ques17 = new Question(
						"Question17",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The indigestible material in the food is known as</b></font>",
						resp,
						"24494",
						"24494",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Intramolecular forces</font>","<font face=Arial size=2> Intermolecular forces</font>","<font face=Arial size=2> hydrogen bond</font>","<font face=Arial size=2> attractive force</font>");comm="";valu="";ques18 = new Question(
						"Question18",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Which are stronger, intramolecular forces or intermolecular forces?</b></font>",
						resp,
						"24417",
						"24417",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Electrification</font>","<font face=Arial size=2> Induction</font>","<font face=Arial size=2> Force</font>","<font face=Arial size=2> ionization</font>");comm="";valu="";ques19 = new Question(
						"Question19",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>If a piece of soft iron is placed in a magnetic field, it will get magnetized by influence or _______</b></font>",
						resp,
						"24501",
						"24501",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>an acid</font>","<font face=Arial size=2> a base</font>","<font face=Arial size=2> neutral</font>","<font face=Arial size=2> it is impossible to guess</font>");comm="";valu="";ques20 = new Question(
						"Question20",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>If a solution conducts electricity, it is probably:</b></font>",
						resp,
						"24531",
						"24531",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Its crystals are a metallic gray</font>","<font face=Arial size=2> It dissolves in alcohol</font>","<font face=Arial size=2> It forms a violet-colored gas</font>","<font face=Arial size=2> It reacts with hydrogen to form a gas</font>");comm="";valu="";ques21 = new Question(
						"Question21",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Which statement describes a chemical property?</b></font>",
						resp,
						"24427",
						"24427",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Separate two or more compounds ed on their polarities</font>","<font face=Arial size=2> &nbsp;Separate two or more compounds based on their masses</font>","<font face=Arial size=2> &nbsp;Separate two or more compounds based on how strongly they interact with othercompounds</font>","<font face=Arial size=2> &nbsp;More than one of the above</font>");comm="";valu="";ques22 = new Question(
						"Question22",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Chromatography is used to:</b></font>",
						resp,
						"24463",
						"24463",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Temperature pressure</font>","<font face=Arial size=2> Energy</font>","<font face=Arial size=2> Heat</font>","<font face=Arial size=2> Light</font>");comm="";valu="";ques23 = new Question(
						"Question23",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Joule is the unit of</b></font>",
						resp,
						"24423",
						"24423",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>ammonia</font>","<font face=Arial size=2> aluminum</font>","<font face=Arial size=2> methane</font>","<font face=Arial size=2> methanol</font>");comm="";valu="";ques24 = new Question(
						"Question24",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Which substance cannot be decomposed into simpler substances?</b></font>",
						resp,
						"24381",
						"24381",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Provide oil</font>","<font face=Arial size=2> Provide water</font>","<font face=Arial size=2> Provide minerals</font>","<font face=Arial size=2> both a &amp; b</font>");comm="";valu="";ques25 = new Question(
						"Question25",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>A coconut tree provides</b></font>",
						resp,
						"24378",
						"24378",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Magnetic</font>","<font face=Arial size=2> Thermal</font>","<font face=Arial size=2> Optical</font>","<font face=Arial size=2> &nbsp;None</font>");comm="";valu="";ques26 = new Question(
						"Question26",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>_______ materials are those that can be influenced by a magnet</b></font>",
						resp,
						"24503",
						"24503",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Filtration</font>","<font face=Arial size=2> crystallization</font>","<font face=Arial size=2> distillation</font>","<font face=Arial size=2> chromatography</font>");comm="";valu="";ques27 = new Question(
						"Question27",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Rock candy is made by a separation process called ______________</b></font>",
						resp,
						"24394",
						"24394",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Faraday</font>","<font face=Arial size=2> Baird</font>","<font face=Arial size=2> Edison</font>","<font face=Arial size=2> Marconi</font>");comm="";valu="";ques28 = new Question(
						"Question28",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The credit of inventing the television goes to</b></font>",
						resp,
						"24385",
						"24385",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Molecular formulas give you the ratios of the elements in a compound-while structural formulas tell you how many atoms of each element are present</font>","<font face=Arial size=2> Molecular formulas tell you where the atoms in a compound are-while structural formulas don&rsquo;t</font>","<font face=Arial size=2> Molecular formulas don&rsquo;t tell you where the atoms in a compound are-while structural formulas do</font>","<font face=Arial size=2> None of the above is correct</font>");comm="";valu="";ques29 = new Question(
						"Question29",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The difference between a molecular and structural formula is that:</b></font>",
						resp,
						"24526",
						"24526",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Balloon</font>","<font face=Arial size=2> Bicycle</font>","<font face=Arial size=2> Aeroplane</font>","<font face=Arial size=2> None of these</font>");comm="";valu="";ques30 = new Question(
						"Question30",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Wright Brothers are regarded inventors of the</b></font>",
						resp,
						"24431",
						"24431",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Weather</font>","<font face=Arial size=2> Meteors</font>","<font face=Arial size=2> Metals</font>","<font face=Arial size=2> Earthquakes</font>");comm="";valu="";ques31 = new Question(
						"Question31",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Meteorology is the science of</b></font>",
						resp,
						"24433",
						"24433",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Proteins and Minerals</font>","<font face=Arial size=2> Fatsand Carbohydrates</font>","<font face=Arial size=2> Proteins and Carbohydrates</font>","<font face=Arial size=2> Vitamins and Minerals</font>");comm="";valu="";ques32 = new Question(
						"Question32",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>PEM is caused by the deficiency of</b></font>",
						resp,
						"24407",
						"24407",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Huh? Water is an excellent conductor of electricity!</font>","<font face=Arial size=2> Pure water contains very few ions</font>","<font face=Arial size=2> The hydrogen bonding in water cause the molecules to move slowly from one place to another</font>","<font face=Arial size=2> None of the above is correct.</font>");comm="";valu="";ques33 = new Question(
						"Question33",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Why doesn&rsquo;t water conduct electricity well?</b></font>",
						resp,
						"24525",
						"24525",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>filtration</font>","<font face=Arial size=2> crystallization</font>","<font face=Arial size=2> distillation</font>","<font face=Arial size=2> chromatography</font>");comm="";valu="";ques34 = new Question(
						"Question34",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>____________ is a separation technique that uses the boiling points of various substances to separate mixtures</b></font>",
						resp,
						"24393",
						"24393",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Endobiology</font>","<font face=Arial size=2> Exobiology</font>","<font face=Arial size=2> Enterobiology</font>","<font face=Arial size=2> Neobiology</font>");comm="";valu="";ques35 = new Question(
						"Question35",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Study of life in outer space is known as</b></font>",
						resp,
						"24480",
						"24480",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Scandium</font>","<font face=Arial size=2> Sulfar</font>","<font face=Arial size=2> Zinc</font>","<font face=Arial size=2> Potassium</font>");comm="";valu="";ques36 = new Question(
						"Question36",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Which one of these is a non-metal?</b></font>",
						resp,
						"24412",
						"24412",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>proton</font>","<font face=Arial size=2> neutron</font>","<font face=Arial size=2> electron</font>","<font face=Arial size=2> more than one of the above</font>");comm="";valu="";ques37 = new Question(
						"Question37",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>What subatomic particle has a mass of one atomic mass unit?</b></font>",
						resp,
						"24484",
						"24484",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Filtration</font>","<font face=Arial size=2> crystallization</font>","<font face=Arial size=2> distillation</font>","<font face=Arial size=2> chromatography</font>");comm="";valu="";ques38 = new Question(
						"Question38",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Suspensions are best separated by which process?</b></font>",
						resp,
						"24395",
						"24395",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>T. H. Huxley</font>","<font face=Arial size=2> Leeuwenhoek</font>","<font face=Arial size=2> Rudolf Virchow</font>","<font face=Arial size=2> J. C. Bose</font>");comm="";valu="";ques39 = new Question(
						"Question39",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Who among the following described protoplasm as the physical basis of life?</b></font>",
						resp,
						"24466",
						"24466",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Star</font>","<font face=Arial size=2> Huge Planet</font>","<font face=Arial size=2> Satellite</font>","<font face=Arial size=2> Comet</font>");comm="";valu="";ques40 = new Question(
						"Question40",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The Sun is a</b></font>",
						resp,
						"24399",
						"24399",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Weak muscles and soft bones</font>","<font face=Arial size=2> Strong bones and strong muscles</font>","<font face=Arial size=2> Poor eyesight</font>","<font face=Arial size=2> Poor breathing capacity</font>");comm="";valu="";ques41 = new Question(
						"Question41",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Calcium deficiency can cause</b></font>",
						resp,
						"24478",
						"24478",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Kwashiorkor</font>","<font face=Arial size=2> Obesity</font>","<font face=Arial size=2> Anemia</font>","<font face=Arial size=2> Scurvy</font>");comm="";valu="";ques42 = new Question(
						"Question42",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Condition of fat person is called -</b></font>",
						resp,
						"24470",
						"24470",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Milk</font>","<font face=Arial size=2> Groundnut</font>","<font face=Arial size=2> Tomato</font>","<font face=Arial size=2> Raw potato</font>");comm="";valu="";ques43 = new Question(
						"Question43",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Which of the following food turns blue-black with iodine solution?</b></font>",
						resp,
						"24404",
						"24404",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Tasting its leaves</font>","<font face=Arial size=2> smelling its levaes</font>","<font face=Arial size=2> by seeing</font>","<font face=Arial size=2> none of the above</font>");comm="";valu="";ques44 = new Question(
						"Question44",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Wrong way to test unknown plants is by:</b></font>",
						resp,
						"24377",
						"24377",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>gravitational contraction.</font>","<font face=Arial size=2> nuclear fission.</font>","<font face=Arial size=2> chemical reactions.</font>","<font face=Arial size=2> nuclear fusion</font>");comm="";valu="";ques45 = new Question(
						"Question45",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The source of energy that keeps the Sun shining today is</b></font>",
						resp,
						"24490",
						"24490",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>twice as great.</font>","<font face=Arial size=2> four times as great</font>","<font face=Arial size=2> one-fourth as great</font>","<font face=Arial size=2> the same as it is now.</font>");comm="";valu="";ques46 = new Question(
						"Question46",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>If the Moon were positioned twice as far from the Earth as it is now, the gravitational attraction would be</b></font>",
						resp,
						"24513",
						"24513",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Measurement</font>","<font face=Arial size=2> inference</font>","<font face=Arial size=2> deduction</font>","<font face=Arial size=2> hypothesis</font>");comm="";valu="";ques47 = new Question(
						"Question47",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The three methods of science are observation, experimentation and _______</b></font>",
						resp,
						"24512",
						"24512",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>twice as great</font>","<font face=Arial size=2> four times as great</font>","<font face=Arial size=2> one-fourth as great</font>","<font face=Arial size=2> the same as it is now</font>");comm="";valu="";ques48 = new Question(
						"Question48",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>If the Moon were positioned twice as far from the Earth as it is now, the gravitational attraction would be</b></font>",
						resp,
						"24517",
						"24517",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Iodine</font>","<font face=Arial size=2> Calcium</font>","<font face=Arial size=2> Iron</font>","<font face=Arial size=2> Phosphorus</font>");comm="";valu="";ques49 = new Question(
						"Question49",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Formation of blood requires</b></font>",
						resp,
						"24405",
						"24405",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>chemical reactions</font>","<font face=Arial size=2> converting kinetic energy into electricity</font>","<font face=Arial size=2> converting gravitational potential energy into electricity</font>","<font face=Arial size=2> nuclear fission</font>");comm="";valu="";ques50 = new Question(
						"Question50",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>How do human-built nuclear power plants on Earth generate energy?</b></font>",
						resp,
						"24527",
						"24527",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Carbohydrate</font>","<font face=Arial size=2> Fat</font>","<font face=Arial size=2> Protein</font>","<font face=Arial size=2> Vitamin</font>");comm="";valu="";ques51 = new Question(
						"Question51",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Starch is a kind of</b></font>",
						resp,
						"24388",
						"24388",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>They have similar sizes</font>","<font face=Arial size=2> They have similar electronegativities</font>","<font face=Arial size=2> Nonmetals prefer to share electrons rather than transfer them</font>","<font face=Arial size=2> None of the above</font>");comm="";valu="";ques52 = new Question(
						"Question52",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Why do two nonmetals generally form covalent bonds with one another?</b></font>",
						resp,
						"24498",
						"24498",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>compounds with water molecules attached to them</font>","<font face=Arial size=2> compounds that have had their water molecules removed</font>","<font face=Arial size=2> compounds that have been heated to high temperatures</font>","<font face=Arial size=2> none of these</font>");comm="";valu="";ques53 = new Question(
						"Question53",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Hydrates are defined as:</b></font>",
						resp,
						"24497",
						"24497",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Wheat</font>","<font face=Arial size=2> Sweet potato</font>","<font face=Arial size=2> Sugarcane</font>","<font face=Arial size=2> Nuts</font>");comm="";valu="";ques54 = new Question(
						"Question54",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Find the odd one out:</b></font>",
						resp,
						"24400",
						"24400",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Water maintains the body temperature</font>","<font face=Arial size=2> Water helps in transportation of nutrients to and from the cells</font>","<font face=Arial size=2> Water is essential for the existence of life</font>","<font face=Arial size=2> About one fourth of our body weight is water</font>");comm="";valu="";ques55 = new Question(
						"Question55",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Which of the following statements is false?</b></font>",
						resp,
						"24459",
						"24459",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>lithium</font>","<font face=Arial size=2> boron</font>","<font face=Arial size=2> nitrogen</font>","<font face=Arial size=2> more than one of the above</font>");comm="";valu="";ques56 = new Question(
						"Question56",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Which of the following elements has three valence electrons?</b></font>",
						resp,
						"24410",
						"24410",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Study of bones</font>","<font face=Arial size=2> Study of muscles</font>","<font face=Arial size=2> Study of architecture</font>","<font face=Arial size=2> Study of languages</font>");comm="";valu="";ques57 = new Question(
						"Question57",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Philology is the</b></font>",
						resp,
						"24432",
						"24432",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>back and forth direction</font>","<font face=Arial size=2> all direction</font>","<font face=Arial size=2> only in back direction</font>","<font face=Arial size=2> none of the above</font>");comm="";valu="";ques58 = new Question(
						"Question58",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>In which direction does the hinge joint allow movements?</b></font>",
						resp,
						"24425",
						"24425",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Coconut oil</font>","<font face=Arial size=2> Groundnut oil</font>","<font face=Arial size=2> Butter</font>","<font face=Arial size=2> Mustard oil</font>");comm="";valu="";ques59 = new Question(
						"Question59",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Which of the following is a source of fats obtained from animals?</b></font>",
						resp,
						"24519",
						"24519",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Dyne</font>","<font face=Arial size=2> Pascal</font>","<font face=Arial size=2> Newton</font>","<font face=Arial size=2> joule</font>");comm="";valu="";ques60 = new Question(
						"Question60",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The SI unit of force is</b></font>",
						resp,
						"24421",
						"24421",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Marconi</font>","<font face=Arial size=2> James Watt</font>","<font face=Arial size=2> Thomas Savery</font>","<font face=Arial size=2> Wright Brothers</font>");comm="";valu="";ques61 = new Question(
						"Question61",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Who among following invented the steam engine?</b></font>",
						resp,
						"24384",
						"24384",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Hasn&rsquo;t dissolved as much solute as is theoretically possible</font>","<font face=Arial size=2> Has dissolved exactly as much solute as is theoretically possible</font>","<font face=Arial size=2> Is unstable because it has dissolved more solute than would be expected</font>","<font face=Arial size=2> none of these</font>");comm="";valu="";ques62 = new Question(
						"Question62",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>An unsaturated solution:</b></font>",
						resp,
						"24510",
						"24510",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>In suspensions the particles eventually settle to the bottom</font>","<font face=Arial size=2> In colloids the particles eventually settle to the bottom</font>","<font face=Arial size=2> In colloids-the solute is permanently dissolved in the solvent</font>","<font face=Arial size=2> None of these</font>");comm="";valu="";ques63 = new Question(
						"Question63",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The main difference between a suspension and a colloid is that:</b></font>",
						resp,
						"24509",
						"24509",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Protein.</font>","<font face=Arial size=2> Vitamin.</font>","<font face=Arial size=2> Cellulose.</font>","<font face=Arial size=2> Carbohydrate</font>");comm="";valu="";ques64 = new Question(
						"Question64",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The energy supplier component of food is-</b></font>",
						resp,
						"24469",
						"24469",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>iron oxide</font>","<font face=Arial size=2> iron (II) oxide</font>","<font face=Arial size=2> iron (III) oxide</font>","<font face=Arial size=2> iron (VI) oxide</font>");comm="";valu="";ques65 = new Question(
						"Question65",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The chemical name for Fe<sub>2</sub>O<sub>3</sub> is:</b></font>",
						resp,
						"24496",
						"24496",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Fats</font>","<font face=Arial size=2> Vitamins</font>","<font face=Arial size=2> Carbohydrates</font>","<font face=Arial size=2> Roughage</font>");comm="";valu="";ques66 = new Question(
						"Question66",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Which food component prevents constipation?</b></font>",
						resp,
						"24507",
						"24507",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Energy giving food</font>","<font face=Arial size=2> Body building food</font>","<font face=Arial size=2> Protective food</font>","<font face=Arial size=2> Roughage</font>");comm="";valu="";ques67 = new Question(
						"Question67",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Protein is called</b></font>",
						resp,
						"24476",
						"24476",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Cellulose</font>","<font face=Arial size=2> Glucose</font>","<font face=Arial size=2> Wheat</font>","<font face=Arial size=2> Maize</font>");comm="";valu="";ques68 = new Question(
						"Question68",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Which is the source of instant energy?</b></font>",
						resp,
						"24457",
						"24457",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>400 million years</font>","<font face=Arial size=2> 4.6 billion years</font>","<font face=Arial size=2> 25 million years</font>","<font face=Arial size=2> 10</font>","<font face=Arial size=2>000 years</font>");comm="";valu="";ques69 = new Question(
						"Question69",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>According to modern science, approximately how old is the Sun?</b></font>",
						resp,
						"24518",
						"24518",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Minerals</font>","<font face=Arial size=2> Fats</font>","<font face=Arial size=2> Sugars</font>","<font face=Arial size=2> Proteins</font>");comm="";valu="";ques70 = new Question(
						"Question70",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Glucose and fructose are:</b></font>",
						resp,
						"24390",
						"24390",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Keepers</font>","<font face=Arial size=2> Poles</font>","<font face=Arial size=2> Inductors</font>","<font face=Arial size=2> equator</font>");comm="";valu="";ques71 = new Question(
						"Question71",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Most of the magnetic power appears to be concentrated at certain points of a magnet. These points are called _______</b></font>",
						resp,
						"24523",
						"24523",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>high pressure and high temperature</font>","<font face=Arial size=2> high pressure and low temperature</font>","<font face=Arial size=2> low pressure and high temperature</font>","<font face=Arial size=2> low pressure and low temperature</font>");comm="";valu="";ques72 = new Question(
						"Question72",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Under which conditions are gases most soluble in water?</b></font>",
						resp,
						"24429",
						"24429",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>100<sup>o</sup>C</font>","<font face=Arial size=2> 0<sup>o</sup>C</font>","<font face=Arial size=2> 32<sup>o</sup>C</font>","<font face=Arial size=2> 212<sup>o</sup>C</font>");comm="";valu="";ques73 = new Question(
						"Question73",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The boiling point of water is</b></font>",
						resp,
						"24413",
						"24413",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>A maximum of one electron each</font>","<font face=Arial size=2> A maximum of two electrons each</font>","<font face=Arial size=2> A number of electrons that depends on the energy level</font>","<font face=Arial size=2> A number of electrons that depends on the type of orbital</font>");comm="";valu="";ques74 = new Question(
						"Question74",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Orbitals hold:</b></font>",
						resp,
						"24521",
						"24521",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>0.08m</font>","<font face=Arial size=2> 0.080 cm</font>","<font face=Arial size=2> 800 cm</font>","<font face=Arial size=2> 8.08 cm</font>");comm="";valu="";ques75 = new Question(
						"Question75",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Which measurement contains three significant figures?</b></font>",
						resp,
						"24473",
						"24473",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Carbohydrate</font>","<font face=Arial size=2> Fat</font>","<font face=Arial size=2> Protein</font>","<font face=Arial size=2> Vitamin</font>");comm="";valu="";ques76 = new Question(
						"Question76",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Starch is a kind of</b></font>",
						resp,
						"24514",
						"24514",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Vitamin C</font>","<font face=Arial size=2> Vitamin A</font>","<font face=Arial size=2> Vitamin D</font>","<font face=Arial size=2> Vitamin F</font>");comm="";valu="";ques77 = new Question(
						"Question77",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Find the odd one out</b></font>",
						resp,
						"24506",
						"24506",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Star</font>","<font face=Arial size=2> Huge Planet</font>","<font face=Arial size=2> Satellite</font>","<font face=Arial size=2> Comet</font>");comm="";valu="";ques78 = new Question(
						"Question78",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The Sun is a</b></font>",
						resp,
						"24372",
						"24372",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>synthesis reaction</font>","<font face=Arial size=2> combustion reaction</font>","<font face=Arial size=2> single displacement reaction</font>","<font face=Arial size=2> double displacement reaction</font>");comm="";valu="";ques79 = new Question(
						"Question79",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>When water and carbon dioxide are formed during an exothermic reaction, it&rsquo;s probably a:</b></font>",
						resp,
						"24418",
						"24418",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>They have ordered packing arrangements called &ldquo;lattices&rdquo;</font>","<font face=Arial size=2> They conduct electricity when dissolved in water or molten</font>","<font face=Arial size=2> They have a low melting point but a high boiling point</font>","<font face=Arial size=2> They are brittle</font>");comm="";valu="";ques80 = new Question(
						"Question80",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Which of the following is NOT a property of a salt?</b></font>",
						resp,
						"24452",
						"24452",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>twice as great.</font>","<font face=Arial size=2> four times as great.</font>","<font face=Arial size=2> one-fourth as great</font>","<font face=Arial size=2> the same as it is now.</font>");comm="";valu="";ques81 = new Question(
						"Question81",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>If the Moon were positioned twice as far from the Earth as it is now, the gravitational attraction would be</b></font>",
						resp,
						"24489",
						"24489",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>a substance</font>","<font face=Arial size=2> a compound</font>","<font face=Arial size=2> an element</font>","<font face=Arial size=2> a mixture</font>");comm="";valu="";ques82 = new Question(
						"Question82",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Petroleum is classified chemically as</b></font>",
						resp,
						"24430",
						"24430",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Dalton</font>","<font face=Arial size=2> Democritus</font>","<font face=Arial size=2> Rutherford</font>","<font face=Arial size=2> none of the above answers is correct</font>");comm="";valu="";ques83 = new Question(
						"Question83",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The &ldquo;plum pudding&rdquo; model of the atom was devised by:</b></font>",
						resp,
						"24520",
						"24520",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>3-4</font>","<font face=Arial size=2> 4-5</font>","<font face=Arial size=2> 2-3</font>","<font face=Arial size=2> 0-1</font>");comm="";valu="";ques84 = new Question(
						"Question84",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Our body needs _litres of water every day</b></font>",
						resp,
						"24447",
						"24447",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>dipole-dipole forces only exist between nonpolar molecules</font>","<font face=Arial size=2> dipole-dipole forces occur between polar molecules</font>","<font face=Arial size=2> dipole-dipole forces are caused by the interaction of partial charges on both molecules</font>","<font face=Arial size=2> None of the above are able to distinguish between dipole-dipole forces and hydrogen bonds</font>");comm="";valu="";ques85 = new Question(
						"Question85",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The difference between dipole-dipole forces and hydrogen bonds are that:</b></font>",
						resp,
						"24508",
						"24508",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Starch</font>","<font face=Arial size=2> Proteins</font>","<font face=Arial size=2> Fats</font>","<font face=Arial size=2> Vitamins</font>");comm="";valu="";ques86 = new Question(
						"Question86",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>White portion of an egg turns violet when two drops of copper sulphate and ten drops of caustic soda are added to it. This indicates the presence of</b></font>",
						resp,
						"24402",
						"24402",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>8</font>","<font face=Arial size=2> 9</font>","<font face=Arial size=2> 10</font>","<font face=Arial size=2> 12</font>");comm="";valu="";ques87 = new Question(
						"Question87",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>How many planets are there in our solar system?</b></font>",
						resp,
						"24396",
						"24396",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Fats</font>","<font face=Arial size=2> Vitamins</font>","<font face=Arial size=2> Proteins</font>","<font face=Arial size=2> Starch</font>");comm="";valu="";ques88 = new Question(
						"Question88",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Blue black colour on adding dilute iodine solution in a crushed food item indicates the presence of</b></font>",
						resp,
						"24495",
						"24495",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>pivotal joints</font>","<font face=Arial size=2> ball and socket joints</font>","<font face=Arial size=2> hinge loints</font>","<font face=Arial size=2> none of the above</font>");comm="";valu="";ques89 = new Question(
						"Question89",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Name the joint where our neck joins the head</b></font>",
						resp,
						"24424",
						"24424",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Weather</font>","<font face=Arial size=2> Meteors</font>","<font face=Arial size=2> Metals</font>","<font face=Arial size=2> Earthquakes</font>");comm="";valu="";ques90 = new Question(
						"Question90",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Meteorology is the science of</b></font>",
						resp,
						"24383",
						"24383",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Absorb energy</font>","<font face=Arial size=2> Give off energy</font>","<font face=Arial size=2> Have no energy change</font>","<font face=Arial size=2> It is impossible to predict the energy change of an exothermic process.</font>");comm="";valu="";ques91 = new Question(
						"Question91",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>&ldquo;Exothermic&rdquo; processes:</b></font>",
						resp,
						"24439",
						"24439",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>No bonds need to be broken to melt a covalent compound</font>","<font face=Arial size=2> The intermolecular forces in ionic compounds are weaker than those in covalent compounds</font>","<font face=Arial size=2> Covalent molecules have higher electron affinities than ionic molecules</font>","<font face=Arial size=2> None of the above is correct</font>");comm="";valu="";ques92 = new Question(
						"Question92",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Why do covalent compounds usually have lower melting and boiling points than ionic compounds?</b></font>",
						resp,
						"24499",
						"24499",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>density</font>","<font face=Arial size=2> mass</font>","<font face=Arial size=2> acidity</font>","<font face=Arial size=2> solubility</font>");comm="";valu="";ques93 = new Question(
						"Question93",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>An example of a chemical property is:</b></font>",
						resp,
						"24438",
						"24438",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Saturated</font>","<font face=Arial size=2> unsaturated</font>","<font face=Arial size=2> concentrated</font>","<font face=Arial size=2> dilute</font>");comm="";valu="";ques94 = new Question(
						"Question94",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>A solution in which the crystallizing rate of the solute equals the dissolving rate of the solute must be</b></font>",
						resp,
						"24428",
						"24428",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>positive</font>","<font face=Arial size=2> negative</font>","<font face=Arial size=2> either positive or negative</font>","<font face=Arial size=2> indeterminate</font>");comm="";valu="";ques95 = new Question(
						"Question95",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The work done to a system is characterized as</b></font>",
						resp,
						"24482",
						"24482",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>mass</font>","<font face=Arial size=2> electric charge</font>","<font face=Arial size=2> mass divided by electric charge</font>","<font face=Arial size=2> none of these</font>");comm="";valu="";ques96 = new Question(
						"Question96",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Mass spectrometers separate isotopes of different elements based on their:</b></font>",
						resp,
						"24486",
						"24486",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Caustic soda</font>","<font face=Arial size=2> Salt</font>","<font face=Arial size=2> HCl</font>","<font face=Arial size=2> Iodine</font>");comm="";valu="";ques97 = new Question(
						"Question97",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Starch is tested with solution of:</b></font>",
						resp,
						"24391",
						"24391",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>filtration</font>","<font face=Arial size=2> crystallization</font>","<font face=Arial size=2> distillation</font>","<font face=Arial size=2> chromatography</font>");comm="";valu="";ques98 = new Question(
						"Question98",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>The process used to separate heterogeneous mixtures of solids and liquids is called ____________</b></font>",
						resp,
						"24392",
						"24392",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);resp=new Array("<font face=Arial size=2>Oxygen</font>","<font face=Arial size=2> Nitrogen</font>","<font face=Arial size=2> Carbon</font>","<font face=Arial size=2> Petrol</font>");comm="";valu="";ques99 = new Question(
						"Question99",
						0,
						"<font face=Arial size=2><b><u>Directions:</u></b> </font><p><font face=Arial size=2><b>Which of the following is necessary for burning (combustion)?</b></font>",
						resp,
						"24444",
						"24444",
						"",
						0,
						0,
						"26gen",
						"1",
						0
						);questions = new Array (ques0,ques1,ques2,ques3,ques4,ques5,ques6,ques7,ques8,ques9,ques10,ques11,ques12,ques13,ques14,ques15,ques16,ques17,ques18,ques19,ques20,ques21,ques22,ques23,ques24,ques25,ques26,ques27,ques28,ques29,ques30,ques31,ques32,ques33,ques34,ques35,ques36,ques37,ques38,ques39,ques40,ques41,ques42,ques43,ques44,ques45,ques46,ques47,ques48,ques49,ques50,ques51,ques52,ques53,ques54,ques55,ques56,ques57,ques58,ques59,ques60,ques61,ques62,ques63,ques64,ques65,ques66,ques67,ques68,ques69,ques70,ques71,ques72,ques73,ques74,ques75,ques76,ques77,ques78,ques79,ques80,ques81,ques82,ques83,ques84,ques85,ques86,ques87,ques88,ques89,ques90,ques91,ques92,ques93,ques94,ques95,ques96,ques97,ques98,ques99);sectionArr0 = new Section(
			"Section 1",
			"1",
			"100",
			"6000",
			"1",
			"0",
			0,
			0);
		sectionArr = new Array (sectionArr0);